[package]
name = "softtube-error"
version = "0.1.0"
authors = ["Per Hultqvist <per@softteam.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
